/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/land.glb --transform --keepnames 
Files: public/models/land.glb [771.69KB] > /home/jerin/Documents/Codding/Projects/Portfolio/Changed Portfolio/land-transformed.glb [1.49MB] (-92%)
Author: Shahriar Shahrabi (https://sketchfab.com/shahriyarshahrabi)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/the-vast-land-733b802f5a4743ef99ad574279d49920
Title: The Vast Land
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/land-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="MainMeshOtuline_Outline_0" geometry={nodes.MainMeshOtuline_Outline_0.geometry} material={materials.Outline} position={[0.22, 0.445, 0.02]} rotation={[-Math.PI / 2, 0, 0]} scale={1.824} />
      <mesh name="MainMeshBounds_SmallObjectsOpaque_0" geometry={nodes.MainMeshBounds_SmallObjectsOpaque_0.geometry} material={materials.SmallObjectsOpaque} rotation={[-Math.PI / 2, 0, 0]} scale={10.11} />
      <mesh name="MainMesh_Material_0" geometry={nodes.MainMesh_Material_0.geometry} material={materials.Material} position={[0.224, 0.466, 0.023]} rotation={[-Math.PI / 2, 0, 0]} scale={1.807} />
      <mesh name="SmallObjects_SmallObjectTransparent_0" geometry={nodes.SmallObjects_SmallObjectTransparent_0.geometry} material={materials.SmallObjectTransparent} position={[0.099, 0.076, -0.307]} rotation={[-Math.PI / 2, 0, 0]} scale={1.367} />
    </group>
  )
}

useGLTF.preload('/land-transformed.glb')
